### ISSUE TITLE
run-ptrace-mapper and run-ptrace-misc testcases fail on aarch64 and possible fix

### ISSUE THREAD

**Issue by ziyangc97** [libunwind/libunwind#557]
The following make check ptrace-related tests fail on openEuler operating system aarch64.

**FAIL: run-ptrace-mapper
FAIL: run-ptrace-misc**

Below is tests/test-suite.log
```
FAIL: run-ptrace-mapper
=======================

unw_get_proc_info(ip=0xaaaae6120810) failed: ret=-10
unw_get_proc_info(ip=0xaaaae6120814) failed: ret=-10
unw_get_proc_info(ip=0xaaaae6120818) failed: ret=-10
unw_get_proc_info(ip=0xaaaae612081c) failed: ret=-10
child terminated by signal 14
FAILURE: detected 5 errors
FAIL run-ptrace-mapper (exit status: 255)

FAIL: run-ptrace-misc
=====================

unw_get_proc_info(ip=0xaaaac5080830) failed: ret=-10
unw_get_proc_info(ip=0xaaaac5080834) failed: ret=-10
unw_get_proc_info(ip=0xaaaac5080838) failed: ret=-10
unw_get_proc_info(ip=0xaaaac508083c) failed: ret=-10
unw_get_proc_info(ip=0xaaaac50807f0) failed: ret=-10
unw_get_proc_info(ip=0xaaaac50807f4) failed: ret=-10
unw_get_proc_info(ip=0xaaaac50807f8) failed: ret=-10
unw_get_proc_info(ip=0xaaaac50807fc) failed: ret=-10
FAILURE: detected 8 errors
FAIL run-ptrace-misc (exit status: 255)

```

From the test-suite.log, we found that unw_get_proc_info print error messge and return -10 which is UNW_ENOINFO(no unwind info found).
By comparing the implementation of unw_get_proc_info() between aarch64 and x86-64 architecture, we discover that in x86-64 the unw_get_proc_info() has following code which promise the test case won't fail
```
  if (dwarf_make_proc_info (&c->dwarf) < 0)
    {
      /* On x86-64, some key routines such as _start() and _dl_start()
         are missing DWARF unwind info.  We don't want to fail in that
         case, because those frames are uninteresting and just mark
         the end of the frame-chain anyhow.  */
      memset (pi, 0, sizeof (*pi));
      pi->start_ip = c->dwarf.ip;
      pi->end_ip = c->dwarf.ip + 1;
      return 0;
    }
  *pi = c->dwarf.pi;
  return 0;
}
```
so we propose the following patch to prevent run-ptrace-mapper and run-ptrace-misc test case from failing.
```
diff --git a/src/aarch64/Gget_proc_info.c b/src/aarch64/Gget_proc_info.c
index c363d24..04c4326 100644
--- a/src/aarch64/Gget_proc_info.c
+++ b/src/aarch64/Gget_proc_info.c
@@ -31,8 +31,13 @@ unw_get_proc_info (unw_cursor_t *cursor, unw_proc_info_t *pi)
   int ret;
 
   ret = dwarf_make_proc_info (&c->dwarf);
-  if (ret < 0)
-    return ret;
+  if (ret < 0) {
+    /* Construct a dummy proc info if Dwarf failed */
+    memset (pi, 0, sizeof (*pi));
+    pi->start_ip = c->dwarf.ip;
+    pi->end_ip = c->dwarf.ip + 4;
+    return 0;
+  }
 
   *pi = c->dwarf.pi;
   return 0;
-- 
```

Is this fix correct?  We are very happy to hear advice or suggestions. Appreciate for any response

**Comment by lemul** [comment]
Perhaps this should be fixed at OS level, if I understand symptoms correctly,
eg https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=5edf3d9fd6efe06fda37b2a460e60690a90457a4
or https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/aarch64/clone.S;h=b1ab5e5d34923a4dfe64446e094156112a00eba2;hb=refs/heads/master#l74

mostly due to https://dwarfstd.org/doc/Dwarf3.pdf - page 118:
  - If a Return Address register is defined in the virtual unwind table,
  and its rule is undefined (for example, by DW_CFA_undefined), then
  there is no return address and no call address, and the virtual
  unwind of stack activations is complete.

**Comment by he7850** [comment]
add some print info inside testcase function do_backtrace():
```
=== loop_cnt 7 ===
=== stack === [n = 0]
  0x400780 <_init + 0xb0>
=== unw_get_proc_info === [n = 0]
unw_get_proc_info(ip=0x400780) failed: ret=-10

=== loop_cnt 8 ===
=== stack === [n = 0]
  0x400780 <_init + 0xb4>
=== unw_get_proc_info === [n = 0]
unw_get_proc_info(ip=0x400780) failed: ret=-10

=== loop_cnt 185 ===
=== stack === [n = 0]
  0x4007a0 <_init + 0xd0>
=== unw_get_proc_info === [n = 0]
unw_get_proc_info(ip=0x4007a0) failed: ret=-10

=== loop_cnt 186 ===
=== stack === [n = 0]
  0x4007a0 <_init + 0xd4>
=== unw_get_proc_info === [n = 0]
unw_get_proc_info(ip=0x4007a0) failed: ret=-10
```
each time unw_get_proc_info() failed, current stack frame is at "_init" function, and the full stack is:
```
  0x4007a4 <_init + 0xd4>
  0x400900 <main + 0x100>
  0xffffa80acf3c <__libc_init_first + 0x7c>
  0xffffa80ad008 <__libc_start_main + 0x94>
  0x400970 <_start + 0x30>
```

**Comment by he7850** [comment]
> Perhaps this should be fixed at OS level, if I understand symptoms correctly, eg https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=5edf3d9fd6efe06fda37b2a460e60690a90457a4
> 
this commit "aarch64: Add unwind information to _start" I think is for the function "_start", not the "_init" function.
by the way, I don't know what this "_init" function is and where it comes from, does anyone know about this function?

**Comment by lemul** [comment]
> > Perhaps this should be fixed at OS level, if I understand symptoms correctly, eg https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=5edf3d9fd6efe06fda37b2a460e60690a90457a4
> 
> this commit "aarch64: Add unwind information to _start" I think is for the function "_start", not the "_init" function. by the way, I don't know what this "_init" function is and where it comes from, does anyone know about this function?

_init called from __libc_start_main, AFAIU init can't be dwarf annotated, however gdb on x86_64 happy with it unlike gdb & libunwind on aarch64. Simple test program here https://people.freebsd.org/~dchagin/i.c

**Comment by he7850** [comment]
after https://github.com/libunwind/libunwind/pull/576, testcase run-ptrace-misc has turned successful, but run-ptrace-mapper still fails:
```
FAIL: run-ptrace-mapper
=======================

child terminated by signal 14
FAILURE: detected 1 errors
FAIL run-ptrace-mapper (exit status: 255)
```
it fails because the child process timed out after 80 seconds of execution.
![image](https://github.com/libunwind/libunwind/assets/6997059/cadcf12a-0701-4e66-aaae-85b6d63a8925)

**Comment by he7850** [comment]
Reasons for timeout:
1. expected exiting path
After child sends SIGUSR1 signal, parent process sets `state` variable to 0, and call do_backtrace() to trace child stack(also print stack frame if verbose mode), and calls `ptrace(PTRACE_SINGLESTEP, ...)` to single-step run the child process.
![image](https://github.com/libunwind/libunwind/assets/6997059/2f7f4f79-34ae-49f3-8d68-ac807d6c09cf)
![image](https://github.com/libunwind/libunwind/assets/6997059/e7251252-9489-4048-a9b0-30f427ce0f12)
After child process steps to send SIGUSR2 signal, parent process sets the state to 0 and calls ptrace (PTRACE_CONT, ...) to let the child process continue and normally exit.
2. Add variable ptrace_cnt to record the number of ptrace calls, found that:
In successful case, after the child process executes single-step for less than 1k times, the child process sends SIGUSR2 signal.
In failed case, the child process fails to reach kill() after 10k+ ptrace step execution and stucks in deadloop.
After adding stack print, found that child process is stuck in `printf` stack:
![image](https://github.com/libunwind/libunwind/assets/6997059/41bf04d1-8e62-4a2f-99a0-36a53f88db1d)

**Comment by he7850** [comment]
### the reason of printf blocking child process
In ARMv8.0 ISA, gcc uses LL-SC(Load Linked and Store Conditional) routine to realize atomic instruction; for ARMv8.1-A and later ISA, gcc supports using the original atomic instruction when -moutline-atomics option is used(after gcc 10.1, this option is enabled default).
An article about this topic: https://cpufun.substack.com/p/atomics-in-aarch64

In glibc `putchar`, it needs to acquire `stdout` lock, which is an atomic action:
![image](https://github.com/libunwind/libunwind/assets/6997059/bbdbf80f-de5d-451e-beda-2eb1582a7329)
In ARMv8.0 platform, this atomic action is compiled to use the LL-SC way:
![image](https://github.com/libunwind/libunwind/assets/6997059/80b420a5-10fd-4e37-8f23-1feb1d96944c)

In this testcase, this atomic action will be stuck into dead loop:
1. If there are other cpu accessing the `stdout` lock variable between the `stxr` and `ldaxr` instruction, LL-SC atomic routine check will fail and retry the whole atomic routine
2. In this testcase, because of ptrace single-step execution, each time child executes an instruction, the parent process will do do_backtrace() and some other operations
3. parent process accesses the stdout lock, and causes child process putchar stuck in atomic routine's loop.

Comparing with the stack print info, it shows the deadloop location is exactly where LL-SC retried the atomic instruction:
<putchar+0x50>, which is `<putchar+80>: cbnz	w3, 0xfffff7e8d994 <putchar+68>`

so, calling printf function between sending SIGUSR1 and SIGUR2 in child main will cause timeout in ARMv8.0 platform.
Suggest to replace printf with any other function, which does not need atomic action.
